# Generated by Django 2.2 on 2019-04-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grid',
        ),
    ]
